question_data = [
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Linus Torvalds created Linux and Git.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The logo for Snapchat is a Bell.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Ada Lovelace is often considered the first computer programmer.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"MacOS is based on Linux.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"AMD created the first consumer 64-bit processor.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"hard","question":"DHCP stands for Dynamic Host Configuration Port.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"&quot;HTML&quot; stands for Hypertext Markup Language.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"Early RAM was directly seated onto the motherboard and could not be easily removed.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The Windows 7 operating system has six main editions.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The Windows ME operating system was released in the year 2000.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The first dual-core CPU was the Intel Pentium D.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Linux was first created as an alternative to Windows XP.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"Android versions are named in alphabetical order.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"A Boolean value of &quot;0&quot; represents which of these words?","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Mathematics","type":"boolean","difficulty":"medium","question":"The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the squares of the other two sides.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Mathematics","type":"boolean","difficulty":"medium","question":"The proof for the Chinese Remainder Theorem used in Number Theory was NOT developed by its first publisher, Sun Tzu.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Mathematics","type":"boolean","difficulty":"easy","question":"The &#039;Squaring the Circle&#039; problem is solvable.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Mathematics","type":"boolean","difficulty":"hard","question":"The binary number &quot;101001101&quot; is equivalent to the Decimal number &quot;334&quot;","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Mathematics","type":"boolean","difficulty":"medium","question":"Zero factorial is equal to zero. ","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Mathematics","type":"boolean","difficulty":"medium","question":"A &#039;Millinillion&#039; is a real number.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Mathematics","type":"boolean","difficulty":"hard","question":"L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Mathematics","type":"boolean","difficulty":"medium","question":"You can square root a negative number with an imaginary number &quot;i&quot;.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Science: Mathematics","type":"boolean","difficulty":"easy","question":"A scalene triangle has two sides of equal length.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Science: Mathematics","type":"boolean","difficulty":"easy","question":"An equilateral triangle always has every angle measuring 60&deg;.","correct_answer":"True","incorrect_answers":["False"]}
]

